- Makefile
- config/crd/bases/risingwave.singularity-data.com_risingwaves.yaml
- config/risingwave-operator.yaml
- docker/Dockerfile
- pkg/manager/compute.go
- pkg/manager/consts.go
- template/compute-config.yaml
1. use file template for compute-config.yaml
2. update compute-config
3. rm redundant const
> fix: update compute node config

- .github/workflows/docker_build_operator.yml
> fix(ci): use event number in image tag

- pkg/manager/frontend.go
> change frontend-v2 to frontend

- pkg/manager/consts.go
> fix: add consts for s3

- apis/risingwave/v1alpha1/consts.go
- apis/risingwave/v1alpha1/defaulter.go
- pkg/controllers/risingwave/risingwave_controller.go
> fix:delete compactor bug

- pkg/manager/compute.go
- template/compute-config.yaml
> fix: compute node config is not valid

- docs/rfc/0000_template.md
- Make a directory for docs and add a template for RFCs
> chore: create a dir for docs and add a RFC template

- docs/rfc/0000_template.md
- Fix a typo introduced in #46
> fix(typo): fix typo in RFC template.

- README.md
add S3 instruction in README.md
> docs: add S3 instruction in README.md

- README.md
> chore: fix a typo in readme

- .github/workflows/ci.yaml
- .github/workflows/docker_build_minio.yml
- .github/workflows/docker_build_operator.yml
- .github/workflows/e2e.yaml
- Disable the checks for draft PRs.
close #54
> feat(ci): disable the checks for draft PRs

- .github/pull_request_template.md
- Fix a grammar issue in this template.
> chore: fix a grammar issue in PR template

- README.md
- Grammarly helps me improve the readme
> chore: improve the readme, Grammarly helps a lot (lol)

- docs/rfc/0001_ctrlkit.md
- Update the status of the ctrlkit RFC
> chore: update status of the ctrlkit RFC

- apis/risingwave/v1alpha1/consts.go
- apis/risingwave/v1alpha1/defaulter.go
- Remove the unnecessary finalizers in the defaulter. 
- After merging #61, the resources are organized with owner references, and deletion is always propagated while deleting with the CLI (but note that when deleting programmatically, you should be careful with the delete option).
> refactor: remove the unnecessary finalizers in the defaulter

- go.mod
- go.sum
- pkg/controller/risingwave_controller.go
- pkg/controller/risingwave_controller_test.go
- Improve the controller test
#79
> test(controller): provide utilities and improve the controller test

- .pre-commit-config.yaml
- apis/risingwave/v1alpha1/risingwave_types.go
- apis/risingwave/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/risingwave.singularity-data.com_risingwaves.yaml
- config/risingwave-operator-test.yaml
- config/risingwave-operator.yaml
- Support pre-commit hooks with [pre-commit](https://pre-commit.com/)
- Misc updates to pass the hooks
Install `pre-commit` command and install the pre-commit hooks locally:
```bash
pre-commit install
```
Each `git commit` operation will trigger the hooks:
```bash
git commit -s
[WARNING] The 'rev' field of repo 'https://github.com/dnephin/pre-commit-golang' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often …
```
> chore: support pre-commit hook with pre-commit

- .github/workflows/docker_build_operator.yml
- Fix nightly date tag
fix the problem in #89
> ci: fix nightly date

- docs/dev/development.md
- Use `jsonc` to show JSON with comments
> chore: update docs/dev/development.md

- .mergify.yml
- Introduce and configure mergify.
> chore: configure mergify

- README.md
- Fix the host name of ClusterIP
> docs: fix the readme

- pkg/manager/risingwave_controller_manager_impl.go
- Fix the global replicas to check.
😅 I think we need unit tests to ensure that. I'll open another PR afterward.
> fix(controller): fix the global replicas to check

- .cspell/doc.txt
- .github/workflows/ci.yaml
- README.md
- cspell.json
> ci: support code coverage report with codecov

- .gitignore
- README.md
- monitoring/prometheus-remote-write-aws.yaml
> chore: guidance to set up the remote write to AWS Prometheus

- examples/risingwave-etcd-auth.yaml
- pkg/factory/risingwave_object_factory.go
- pkg/factory/risingwave_object_factory_test.go
- As mentioned in the title.
singularity-data/risingwave#4070
close #117
> feat(controller): support authentication between meta and etcd

- cmd/manager/manager.go
- pkg/controller/risingwave_controller.go
- pkg/controller/risingwave_controller_test.go
- Add unit tests for the `RisingWaveController`
- Remove the useless parameter in `NewRisingWaveController`
close #79
> test: add unit tests for controller

- pkg/factory/risingwave_object_factory.go
- As mentioned in the title
- add argument `--client-address`
https://github.com/singularity-data/risingwave-operator/issues/133
> feat: add argument `--client-address` for compute node

- .github/workflows/docker_build_operator.yml
- config/manager/manager.yaml
- config/risingwave-operator.yaml
- Modify the workflow to build images with release tag
- Regenerate the release version of YAML
> chore: release pr

- .github/workflows/docker_build_operator.yml
> fix: fix the workflow for building image

- Makefile
- README.md
- apis/risingwave/v1alpha1/doc.go
- apis/risingwave/v1alpha1/risingwave_pod_template_types.go
- apis/risingwave/v1alpha1/risingwave_types.go
- config/crd/bases/risingwave.singularity-data.com_risingwavepodtemplates.yaml
- config/crd/bases/risingwave.singularity-data.com_risingwaves.yaml
- config/risingwave-operator-test.yaml
- config/risingwave-operator.yaml
- cspell.json
- docs/general/api.md
- scripts/docs/config.json
- scripts/docs/templates/members.tpl
- scripts/docs/templates/pkg.tpl
- scripts/docs/templates/type.tpl
- Improve the comments on API structs
- Support generating the API docs with a modified [gen-crd-api-reference-docs](https://github.com/arkbriar/gen-crd-api-reference-docs)
close #148
> docs & chore: support generating API docs; update the comments of APIs

- README.md
- e2e/e2e.sh
Bump recommended version to v1.9.1
- As title.
- Update the e2e script.
> docs: update install command for cert-manager

- docs/plugin/plugin.md
- pkg/command/describe/describe.go
- Add documentation for all commands currently implemented
> docs: add documentation for kubectl risingwave plugin

- cmd/manager/manager.go
- pkg/controller/hooks.go
- pkg/controller/risingwave_controller.go
- pkg/controller/risingwave_controller_test.go
This PR adds a small amount of events during the lifecycle of a risingwave instance. It does so by adding a postrun hook to the controller.
closes #147
> emit events for risingwave

- .github/workflows/e2e.yaml
- e2e/e2e-plugin
- e2e/e2e.sh
- pkg/command/create/create.go
- pkg/command/deploy/common.go
- pkg/command/deploy/resume.go
- pkg/command/deploy/stop.go
> test: add e2e for plugin

- docs/rfc/0001_ctrlkit.md
- docs/rfc/0003_risingwave_ng.md
> chore: mark rfc 0001, 0003 as completed

- .github/workflows/images.yml
- fix the semver tag: from `0.2.0` to `v0.2.0`
> ci: fix the semver tag

- README.md
- Update the release version in README
> chore: update readme for release

- docs/dev/development.md
> docs: update the development.md

- docs/dev/development.md
Adds documentation on how to run your own operator in your local cluster.
> Run custom operator in local cluster

- README.md
> Docs: prometheus-remote-write-aws.yaml link error

- docker/Dockerfile
Proposal to re-write the docker file. Instead of using bash if-else conditions, we could use a conditional dockerfile (see [here](https://stackoverflow.com/a/60820156/5345715)).
If we have more nested conditions in the future this may make it easier to think about, since each branch gets its own stage.
Please also test if this works on your machine
@Nebulazhang Noticed you wrote the og Dockerfile. What do you think about this approach? 
> Rewrite Dockerfile to conditional dockerfile

- README.md
> docs: update the link of risingwave-operator manifests

- pkg/factory/risingwave_object_factory.go
> feat: set RUST_BACKTRACE=full in containers of RisingWave by default

- apis/risingwave/v1alpha1/risingwave_types.go
- config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
- config/risingwave-operator-test.yaml
- config/risingwave-operator.yaml
- As title.
NOTE: after it is installed, the operator will panic if there are invalid objects but it's fine because the panics will be recovered before being thrown to the controller runtime.
> fix: mark some of the storage fields required

- pkg/factory/risingwave_object_factory.go
> fix: mount config file for frontend pods

- monitoring/README.md
> chore: update prometheus-remote-write-aws.yaml path

- e2e/check.sql
- e2e/env-utils
- e2e/scaleview/scale-view-two-groups.yaml
- e2e/testcases/pod-template/risingwave-spot-toleration.yaml
- examples/risingwave/risingwave-component-groups.yaml
- examples/risingwave/risingwave-component-only.yaml
- examples/risingwave/risingwave-customize-config.yaml
- examples/risingwave/risingwave-etcd-auth.yaml
- examples/risingwave/risingwave-etcd-minio.yaml
- examples/risingwave/risingwave-etcd-s3.yaml
- examples/risingwave/risingwave-in-memory.yaml
- examples/risingwave/risingwave-privileged.yaml
- examples/risingwave/risingwave-spot-toleration.yaml
- examples/risingwavescaleview/sv-example-frontend.yaml
- examples/risingwavescaleview/sv-spot-compactor.yaml
- Remove the `NOT NULL` from `check.sql`, which is not supported now.
- Update the image tags to `ghcr.io/risingwavelabs/risingwave:v0.1.13`.
- Fix e2e image tags.
```plain
ERROR:  QueryError: Feature is not yet implemented: column constraints "NOT NULL"
No tracking issue yet. Feel free to submit a feature request at https://github.com/risingwavelabs/risingwave/issues/new?labels=type%2Ffeature&template=feature_request.yml
```
> chore: update examples and e2e test scripts

- monitoring/README.md
> chore: update the monitoring README

- Makefile
- cmd/plugin/README.md
- docs/plugin/plugin.md
- pkg/command/list/list.go
- Add a readme
- Change help message
- Automatically make newly build plugin available
> Minor changes in the plugin

- .github/workflows/release.yml
- As title. 
Bad news: I have to merge this before I test if it's correctly set. 🥲 
close #162
> ci: add release pipeline

- .github/workflows/release.yml
> ci: setup golang 1.19 before release

- .github/workflows/release.yml
> ci: use the correct action to upload assets

- pkg/controller/risingwave_controller.go
- pkg/controller/risingwave_scale_view_controller.go
- pkg/object/risingwave_manager.go
- pkg/webhook/risingwave_scale_view_mutating_webhook.go
- pkg/webhook/risingwave_scale_view_mutating_webhook_test.go
- optimize the locking and unlocking progress
https://github.com/risingwavelabs/risingwave-operator/issues/261
> feat: optimize the locking and unlocking progress

- pkg/controller/risingwave_controller.go
- pkg/utils/predicates.go
> feat: optimize the scale view unlock by watching on only delete events

- hack/boilerplate.go.txt
- hack/boilerplate.shell.txt
> chore: update license boilerplate to use year 2023

- test/e2e/common/shell.sh
- test/e2e/e2e.sh
> chore: fix e2e scripts to pass shellcheck

- .github/workflows/images.yml
- Build and push images to DockerHub when it's a 
- nightly build
- release build
- latest build on main
fix #247
> ci: support build images to DockerHub

- .github/workflows/images.yml
> ci: try to fix the image workflow

- README.md
> docs: use GKE instead of GCP

- docs/manifests/risingwave/risingwave-component-groups.yaml
- docs/manifests/risingwave/risingwave-component-only.yaml
- docs/manifests/risingwave/risingwave-customize-config.yaml
- docs/manifests/risingwave/risingwave-etcd-auth.yaml
- docs/manifests/risingwave/risingwave-etcd-minio.yaml
- docs/manifests/risingwave/risingwave-etcd-s3.yaml
- docs/manifests/risingwave/risingwave-in-memory.yaml
- docs/manifests/risingwave/risingwave-privileged.yaml
- docs/manifests/risingwave/risingwave-spot-toleration.yaml
- docs/manifests/risingwavescaleview/sv-example-frontend.yaml
- docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
- e2e/env-utils
- test/e2e/env
- test/e2e/tests/tests.sh
- Use v0.1.16 in tests and manifests
fix #337
> chore: update to use risingwave v0.1.16

- pkg/factory/risingwave_object_factory.go
> feat: expose metrics for frontend nodes

- config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
- config/risingwave-operator-test.yaml
- config/risingwave-operator.yaml
- add connector node doc
https://github.com/risingwavelabs/risingwave-operator/pull/345
> docs: add connector node doc

- test/e2e/e2e.sh
- test/e2e/tests/risingwave/manifests/connector/connector-test.yaml
- test/e2e/tests/risingwave/tests.sh
- test/e2e/tests/tests.sh
- add e2e test for connector
https://github.com/risingwavelabs/risingwave-operator/issues/351
> test: add e2e test for connector

- pkg/factory/risingwave_object_factory.go
- Setup `RW_CONNECTOR_RPC_ENDPOINT` in meta
> fix: setup meta env

- pkg/factory/risingwave_object_factory.go
- pkg/factory/risingwave_object_factory_test.go
> fix: fix the env vars for etcd auth

- config/risingwave-operator-test.yaml
- config/risingwave-operator.yaml
- docs/general/api.md
> doc: add version doc

- hack/scripts/install.sh
> feat: add a script for installation

- pkg/manager/risingwave_controller_manager_impl.go
> refactor: correct component log

- pkg/consts/consts.go
- pkg/factory/risingwave_object_factory.go
- pkg/webhook/risingwave_validating_webhook.go
> feat: add JAVA_OPTS

- .golangci.yaml
- go.mod
- pkg/controller/risingwave_controller.go
- pkg/controller/risingwave_scale_view_controller.go
- pkg/ctrlkit/conditional.go
- pkg/ctrlkit/optimize.go
- pkg/ctrlkit/retry.go
- pkg/factory/risingwave_object_factory.go
- pkg/factory/risingwave_object_factory_predicate_test.go
- pkg/manager/risingwave_controller_manager_impl.go
- pkg/manager/risingwave_scale_view_controller_manager_impl.go
- pkg/utils/common.go
- pkg/webhook/risingwave_validating_webhook.go
- Enable `indent-error-flow` rule in `revive`
- Address related issues
> ci: enable indent-error-flow rule in revive

- config/manager/manager.yaml
- config/risingwave-operator-test.yaml
- config/risingwave-operator.yaml
- Update the resources of manager to `100m/100Mi, 500m/500Mi`
> fix: update the resources of manager to avoid OOM

- pkg/factory/risingwave_object_factory.go
> chore(metrics): drop `batch.* & stream_exchage.*` metrics for risingwave

- pkg/factory/risingwave_object_factory.go
> feat: auto config Xmx

- Makefile
- docs/dev/rampup_example.md
- docs/manifests/risingwave/risingwave-aliyun-oss.yaml
- docs/manifests/risingwave/risingwave-component-groups.yaml
- docs/manifests/risingwave/risingwave-component-only.yaml
- docs/manifests/risingwave/risingwave-customize-config.yaml
- docs/manifests/risingwave/risingwave-etcd-auth.yaml
- docs/manifests/risingwave/risingwave-etcd-minio.yaml
- docs/manifests/risingwave/risingwave-etcd-s3.yaml
- docs/manifests/risingwave/risingwave-hdfs.yaml
- docs/manifests/risingwave/risingwave-in-memory.yaml
- docs/manifests/risingwave/risingwave-privileged.yaml
- docs/manifests/risingwave/risingwave-s3-compatible.yaml
- docs/manifests/risingwave/risingwave-spot-toleration.yaml
- docs/manifests/risingwavescaleview/sv-example-frontend.yaml
- docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
- e2e/env-utils
- pkg/utils/common_test.go
- test/e2e/env
- test/e2e/tests/tests.sh
> chore: update image version to v0.18.0

- pkg/controller/meta_pod_role_labeler.go
- pkg/factory/risingwave_object_factory.go
- pkg/utils/common.go
> feat: optimize the pod labeling

- pkg/controller/meta_pod_role_labeler.go
- test/e2e/tests/risingwave/meta.sh
- test/e2e/tests/risingwave/tests.sh
- As the title.
We might need to add test cases to ensure the correctness.
> fix(meta-labeler): fix extracting endpoint from env vars

- pkg/utils/sort.go
> fix: fix TopologicalSort

- pkg/utils/sort_test.go
> test: add topological sort test

- pkg/utils/sort.go
- pkg/utils/sort_test.go
- Use dependency order instead of original order to fix the topological sort. The fake transitive should be avoided by escaping with `$$`
fix #401
> fix: fix the topological sort

- README.md
- docs/general/storage.md
1. move storage into a separate file
2. add azure blob guidance
> docs: move storage into separate file and add azure blob guidance

- docs/manifests/risingwave/risingwave-etcd-s3.yaml
Remove the Secret section to be compatible with the current documentation.
- As title, the removed section will override the Secret thus causing an incorrect deployment. Remove it to avoid problems.
> chore: update risingwave-etcd-s3.yaml

- pkg/utils/sort.go
- pkg/utils/sort_test.go
- test/e2e/e2e.sh
- test/e2e/testenv/util/lib.sh
- test/e2e/tests/risingwave/query.sql
- test/e2e/tests/risingwave/tests.sh
- Fix a problem in the psql execution to run the SQL queries correctly.
#401
> test: fix e2e test

- apis/risingwave/v1alpha1/risingwave_types.go
- config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
- config/risingwave-operator-test.yaml
- config/risingwave-operator.yaml
- docs/dev/rampup_example.md
- docs/general/api.md
- pkg/factory/risingwave_object_factory.go
- pkg/factory/risingwave_object_factory_predicate_test.go
- pkg/manager/risingwave_controller_manager_impl.go
- pkg/testutils/testutils.go
- pkg/utils/common.go
- pkg/webhook/risingwave_conversion.go
- pkg/webhook/risingwave_validating_webhook.go
- pkg/webhook/risingwave_validating_webhook_test.go
> feat: Promote the `image`

- codecov.yml
> ci: allow 0.1% threshold on code coverage delta

- pkg/factory/risingwave_object_factory.go
> fix: set affinity in factory

- README.md
- As title, use the badge from buildkite instead.
> chore: update pipeline barge in readme

- .github/workflows/images.yml
- As title, use full sha as the binary verison.
> ci: set image version

- apis/risingwave/v1alpha1/risingwave_state_store_backend.go
- config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
- config/risingwave-operator-test.yaml
- config/risingwave-operator.yaml
- pkg/controller/risingwave_controller.go
- pkg/webhook/risingwave_validating_webhook.go
- sync and convert storage after upgrading
> feat: sync and convert to v1alpha2 features

- ci/scripts/run-static-checks.sh
> ci: fix run-static-check.sh

- pkg/factory/risingwave_object_factory.go
- pkg/factory/risingwave_object_factory_testcases_test.go
> fix: fix metadata propagation

- .github/workflows/images_cron.yml
- .github/workflows/images_pr.yml
- .github/workflows/license_check.yml
> ci: separate the image pipelines

- docs/manifests/risingwavescaleview/sv-example-frontend.yaml
- docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
- docs/manifests/stable/memory/risingwave.yaml
- docs/manifests/stable/persistent/minio/risingwave.yaml
- docs/manifests/stable/persistent/s3/risingwave.yaml
> docs: fix the manifests and add a set of stable manifests

- .github/workflows/images_cron.yml
- .github/workflows/images_pr.yml
> ci: pass tag as the version in the image CI

- pkg/webhook/risingwave_validating_webhook.go
> fix: fix the field paths in webhook

- cmd/manager/manager.go
> chore: use webhook server

- README.md
- cmd/manager/manager.go
- docs/dev/rampup_example.md
- docs/manifests/risingwave/risingwave-aliyun-oss.yaml
- docs/manifests/risingwave/risingwave-azure.yaml
- docs/manifests/risingwave/risingwave-customize-config.yaml
- docs/manifests/risingwave/risingwave-etcd-auth.yaml
- docs/manifests/risingwave/risingwave-etcd-hdfs.yaml
- docs/manifests/risingwave/risingwave-etcd-local-disk.yaml
- docs/manifests/risingwave/risingwave-etcd-minio.yaml
- docs/manifests/risingwave/risingwave-etcd-s3.yaml
- docs/manifests/risingwave/risingwave-gcs.yaml
- docs/manifests/risingwave/risingwave-in-memory.yaml
- docs/manifests/risingwave/risingwave-s3-compatible.yaml
- docs/manifests/risingwave/risingwave-webhdfs.yaml
- docs/manifests/risingwavescaleview/sv-example-frontend.yaml
- docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
- docs/manifests/stable/memory/risingwave.yaml
- docs/manifests/stable/persistent/minio/risingwave.yaml
- docs/manifests/stable/persistent/s3/risingwave.yaml
- test/e2e/env
- test/e2e/tests/risingwave/manifests/multi-meta/multi-meta.yaml
- test/e2e/tests/risingwave/manifests/storages/object-azure-blob.yaml
- test/e2e/tests/tests.sh
> chore: bump kernel version to v0.19.1

- docs/manifests/risingwave/risingwave-etcd-auth.yaml
- docs/manifests/risingwave/risingwave-etcd-hdfs.yaml
- docs/manifests/risingwave/risingwave-etcd-local-disk.yaml
- docs/manifests/risingwave/risingwave-etcd-minio.yaml
- docs/manifests/risingwave/risingwave-etcd-s3.yaml
As the title.
https://github.com/risingwavelabs/risingwave/blob/ba247f61b68124d6664a6253683de6c7d3f06b16/docker/docker-compose-with-s3.yml#L91
> chore(etcd): add `max-request-bytes` for ETCD opts

- monitoring/install.sh
As the title.
I missed the repo command, and because I added the repo locally, I didn't discover this issue.
> fix(monitoring): add prometheus-community repo in `install.sh`

- README.md
> chore: add compatibility notice for main branch

- apis/risingwave/v1alpha1/risingwave_node_group.go
- config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
- config/risingwave-operator-test.yaml
- config/risingwave-operator.yaml
- docs/general/api.md
> feat: allow any format log level

- monitoring/README.md
> chore(doc): update monitoring readme

- monitoring/kube-prometheus-stack.yaml
Is this the way to add a new dashboard? 
found a dev dashboard quite useful when debugging problems for users
> feat: add a risingwave-dev-dashboard

- docs/manifests/risingwave/risingwave-aliyun-oss.yaml
- docs/manifests/risingwave/risingwave-azure.yaml
- docs/manifests/risingwave/risingwave-customize-config.yaml
- docs/manifests/risingwave/risingwave-etcd-auth.yaml
- docs/manifests/risingwave/risingwave-etcd-hdfs.yaml
- docs/manifests/risingwave/risingwave-etcd-local-disk.yaml
- docs/manifests/risingwave/risingwave-etcd-minio.yaml
- docs/manifests/risingwave/risingwave-etcd-s3.yaml
- docs/manifests/risingwave/risingwave-gcs.yaml
- docs/manifests/risingwave/risingwave-in-memory.yaml
- docs/manifests/risingwave/risingwave-s3-compatible.yaml
- docs/manifests/risingwave/risingwave-webhdfs.yaml
- docs/manifests/risingwavescaleview/sv-example-frontend.yaml
- docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
- docs/manifests/stable/memory/risingwave.yaml
- docs/manifests/stable/persistent/minio/risingwave.yaml
- docs/manifests/stable/persistent/s3/risingwave.yaml
- test/e2e/env
- test/e2e/tests/tests.sh
> chore: update manifests and tests to use v1.0.0

- docs/manifests/stable/persistent/minio/risingwave.yaml
- docs/manifests/stable/persistent/s3/risingwave.yaml
- Add several recommended arguments to etcd, including `--max-request-byte` and `--quota-backend-bytes`
- Increase the PV used by etcd to 10G
- Increase the PV used by MinIO to 100G
> docs: update stable manifests

- docs/general/aws-eks-iam-for-s3.md
> docs: add a doc about using IAM for service account

- docs/general/aws-eks-iam-for-s3.md
- docs/manifests/risingwave/risingwave-aliyun-oss.yaml
- docs/manifests/risingwave/risingwave-azure.yaml
- docs/manifests/risingwave/risingwave-customize-config.yaml
- docs/manifests/risingwave/risingwave-etcd-auth.yaml
- docs/manifests/risingwave/risingwave-etcd-local-disk.yaml
- docs/manifests/risingwave/risingwave-etcd-minio.yaml
- docs/manifests/risingwave/risingwave-etcd-s3.yaml
- docs/manifests/risingwave/risingwave-gcs.yaml
- docs/manifests/risingwave/risingwave-in-memory.yaml
- docs/manifests/risingwave/risingwave-s3-compatible.yaml
- docs/manifests/risingwavescaleview/sv-example-frontend.yaml
- docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
- docs/manifests/stable/memory/risingwave.yaml
- docs/manifests/stable/persistent/minio/risingwave.yaml
- docs/manifests/stable/persistent/s3/risingwave.yaml
- test/e2e/env
- test/e2e/tests/tests.sh
> chore: bump risingwave version to v1.1.0

- docs/general/aws-eks-iam-for-s3.md
- docs/manifests/risingwave/risingwave-aliyun-oss.yaml
- docs/manifests/risingwave/risingwave-azure.yaml
- docs/manifests/risingwave/risingwave-customize-config.yaml
- docs/manifests/risingwave/risingwave-etcd-auth.yaml
- docs/manifests/risingwave/risingwave-etcd-local-disk.yaml
- docs/manifests/risingwave/risingwave-etcd-minio.yaml
- docs/manifests/risingwave/risingwave-etcd-s3.yaml
- docs/manifests/risingwave/risingwave-gcs.yaml
- docs/manifests/risingwave/risingwave-in-memory.yaml
- docs/manifests/risingwave/risingwave-s3-compatible.yaml
- docs/manifests/risingwavescaleview/sv-example-frontend.yaml
- docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
- docs/manifests/stable/memory/risingwave.yaml
- docs/manifests/stable/persistent/minio/risingwave.yaml
- docs/manifests/stable/persistent/s3/risingwave.yaml
- test/e2e/env
- test/e2e/tests/tests.sh
> chore: use v1.1.1 to avoid an issue caused by bumping tonic

- .github/workflows/release.yml
- .golangci.yaml
- build/Dockerfile
- ci/runner/Dockerfile
> chore: bump to go 1.21

- docs/general/aws-eks-iam-for-s3.md
- docs/manifests/risingwave/risingwave-aliyun-oss.yaml
- docs/manifests/risingwave/risingwave-azure.yaml
- docs/manifests/risingwave/risingwave-customize-config.yaml
- docs/manifests/risingwave/risingwave-etcd-auth.yaml
- docs/manifests/risingwave/risingwave-etcd-local-disk.yaml
- docs/manifests/risingwave/risingwave-etcd-minio.yaml
- docs/manifests/risingwave/risingwave-etcd-s3.yaml
- docs/manifests/risingwave/risingwave-gcs.yaml
- docs/manifests/risingwave/risingwave-in-memory.yaml
- docs/manifests/risingwave/risingwave-s3-compatible.yaml
- docs/manifests/risingwavescaleview/sv-example-frontend.yaml
- docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
- docs/manifests/stable/memory/risingwave.yaml
- docs/manifests/stable/persistent/minio/risingwave.yaml
- docs/manifests/stable/persistent/s3/risingwave.yaml
- test/e2e/env
- test/e2e/tests/tests.sh
> chore: bump risingwave image to v1.1.2

- pkg/factory/risingwave_object_factory.go
As the title.
Merge the env vars, and use the container env vars(set in template) to replace the generated default vars, if the key equals.
> feat: merge the env vars and use the vars set by user if key equals

- README.md
- docs/general/aws-eks-iam-for-s3.md
- docs/manifests/risingwave/risingwave-aliyun-oss.yaml
- docs/manifests/risingwave/risingwave-azure.yaml
- docs/manifests/risingwave/risingwave-customize-config.yaml
- docs/manifests/risingwave/risingwave-etcd-auth.yaml
- docs/manifests/risingwave/risingwave-etcd-local-disk.yaml
- docs/manifests/risingwave/risingwave-etcd-minio.yaml
- docs/manifests/risingwave/risingwave-etcd-s3.yaml
- docs/manifests/risingwave/risingwave-gcs.yaml
- docs/manifests/risingwave/risingwave-in-memory.yaml
- docs/manifests/risingwave/risingwave-s3-compatible.yaml
- docs/manifests/risingwavescaleview/sv-example-frontend.yaml
- docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
- docs/manifests/stable/memory/risingwave.yaml
- docs/manifests/stable/persistent/minio/risingwave.yaml
- docs/manifests/stable/persistent/s3/risingwave.yaml
- test/e2e/env
- test/e2e/tests/tests.sh
> chore: bump risingwave version to v1.2.0

- README.md
> docs: Add the Helm chart link

- pkg/factory/risingwave_object_factory.go
As title. Increase the interval to reduce the Prometheus memory.
> chore: increase the default scrape interval

- test/e2e/manifests/tests.sh
After #515, manifest test pipeline will always fail due to insufficient resources.
- Update it with server side dry run to avoid that
> ci: update the manifest test

- README.md
- docs/general/aws-eks-iam-for-s3.md
- docs/manifests/risingwave/risingwave-aliyun-oss.yaml
- docs/manifests/risingwave/risingwave-customize-config.yaml
- docs/manifests/risingwave/risingwave-etcd-auth.yaml
- docs/manifests/risingwave/risingwave-etcd-azure.yaml
- docs/manifests/risingwave/risingwave-etcd-local-disk.yaml
- docs/manifests/risingwave/risingwave-etcd-minio.yaml
- docs/manifests/risingwave/risingwave-etcd-s3.yaml
- docs/manifests/risingwave/risingwave-gcs.yaml
- docs/manifests/risingwave/risingwave-im-memory-azure.yaml
- docs/manifests/risingwave/risingwave-in-memory.yaml
- docs/manifests/risingwave/risingwave-s3-compatible.yaml
- docs/manifests/risingwavescaleview/sv-example-frontend.yaml
- docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
- docs/manifests/stable/memory/risingwave.yaml
- docs/manifests/stable/persistent/minio/risingwave.yaml
- docs/manifests/stable/persistent/s3/risingwave.yaml
- test/e2e/env
- test/e2e/tests/tests.sh
> chore: bump risingwave image version to v1.3.0

- pkg/controller/risingwave_compute_sts_update_strategy.go
> chore: fix typo

- pkg/manager/risingwave_controller_manager.cm
- pkg/manager/risingwave_controller_manager_generated.go
- pkg/manager/risingwave_controller_manager_impl.go
- test/e2e/tests/risingwave/manifests/standalone/standalone.yaml
- test/e2e/tests/risingwave/tests.sh
- Add a E2E testcase so to cover the standalone mode
- Fix a bug that RisingWave can never become ready because it looked for incorrect object name.
Fix #520
> fix & test: add an e2e testcase for standalone deployment, fix bug found

- ci/run-script.sh
- ci/scripts/build.sh
- ci/scripts/run-e2e-tests.sh
- ci/scripts/run-static-checks.sh
- ci/scripts/run-unit-tests.sh
- hack/cspell/dicts/misc.txt
- pkg/factory/risingwave_object_factory.go
distributed and standalone deployment
- Add the lost env back.
- Also fixed the CI.
> fix: fix the regression happened on env RW_META_ADDR, add it in both

- README.md
- docs/general/aws-eks-iam-for-s3.md
- docs/manifests/risingwave/risingwave-aliyun-oss.yaml
- docs/manifests/risingwave/risingwave-customize-config.yaml
- docs/manifests/risingwave/risingwave-etcd-auth.yaml
- docs/manifests/risingwave/risingwave-etcd-azure.yaml
- docs/manifests/risingwave/risingwave-etcd-local-disk.yaml
- docs/manifests/risingwave/risingwave-etcd-minio.yaml
- docs/manifests/risingwave/risingwave-etcd-s3.yaml
- docs/manifests/risingwave/risingwave-gcs.yaml
- docs/manifests/risingwave/risingwave-im-memory-azure.yaml
- docs/manifests/risingwave/risingwave-in-memory.yaml
- docs/manifests/risingwave/risingwave-s3-compatible.yaml
- docs/manifests/risingwave/risingwave-standalone.yaml
- docs/manifests/risingwavescaleview/sv-example-frontend.yaml
- docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
- docs/manifests/stable/memory/risingwave.yaml
- docs/manifests/stable/persistent/minio/risingwave.yaml
- docs/manifests/stable/persistent/s3/risingwave.yaml
- pkg/factory/risingwave_object_factory.go
- test/e2e/env
- test/e2e/tests/tests.sh
- As title. The E2E test is expected to fail since there's no such options in v1.3.0.
Mark it as draft for now until the v1.4 is released.
Fix #522
> feat: use --config-file and --prometheus-listen-addr in standalone mode

- docs/general/state-stores.md
- Correct state store description for Azure Blob Storage
> fix: correct description for azure blob storage

- pkg/controller/risingwave_compute_sts_update_strategy.go
> fix: fix nil reference in sts update controller

- README.md
> chore: bump up risingwave to v1.5.0

- docs/general/aws-eks-iam-for-s3.md
- docs/manifests/risingwave/risingwave-aliyun-oss.yaml
- docs/manifests/risingwave/risingwave-customize-config.yaml
- docs/manifests/risingwave/risingwave-etcd-auth.yaml
- docs/manifests/risingwave/risingwave-etcd-azure.yaml
- docs/manifests/risingwave/risingwave-etcd-local-disk.yaml
- docs/manifests/risingwave/risingwave-etcd-minio.yaml
- docs/manifests/risingwave/risingwave-etcd-s3.yaml
- docs/manifests/risingwave/risingwave-gcs.yaml
- docs/manifests/risingwave/risingwave-im-memory-azure.yaml
- docs/manifests/risingwave/risingwave-in-memory.yaml
- docs/manifests/risingwave/risingwave-s3-compatible.yaml
- docs/manifests/risingwave/risingwave-standalone.yaml
- docs/manifests/risingwavescaleview/sv-example-frontend.yaml
- docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
- docs/manifests/stable/memory/risingwave.yaml
- docs/manifests/stable/persistent/minio/risingwave.yaml
- docs/manifests/stable/persistent/s3/risingwave.yaml
- test/e2e/env
- test/e2e/tests/tests.sh
- Supplementary PR based on #558
> chore: bump RisingWave version to v1.5.0

- docs/general/aws-eks-iam-for-s3.md
- docs/manifests/risingwave/risingwave-aliyun-oss.yaml
- docs/manifests/risingwave/risingwave-customize-config.yaml
- docs/manifests/risingwave/risingwave-etcd-auth.yaml
- docs/manifests/risingwave/risingwave-etcd-azure.yaml
- docs/manifests/risingwave/risingwave-etcd-local-disk.yaml
- docs/manifests/risingwave/risingwave-etcd-minio.yaml
- docs/manifests/risingwave/risingwave-etcd-s3.yaml
- docs/manifests/risingwave/risingwave-gcs.yaml
- docs/manifests/risingwave/risingwave-im-memory-azure.yaml
- docs/manifests/risingwave/risingwave-in-memory.yaml
- docs/manifests/risingwave/risingwave-s3-compatible.yaml
- docs/manifests/risingwave/risingwave-standalone.yaml
- docs/manifests/risingwavescaleview/sv-example-frontend.yaml
- docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
- docs/manifests/stable/memory/risingwave.yaml
- docs/manifests/stable/persistent/minio/risingwave.yaml
- docs/manifests/stable/persistent/s3/risingwave.yaml
- test/e2e/env
- test/e2e/tests/tests.sh
> Bump RisingWave to v1.5.1

- docs/manifests/risingwave/advanced/separate-batch-streaming-modes.yaml
- Based on [docs/manifests/risingwave/risingwave-etcd-s3.yaml](https://github.com/risingwavelabs/risingwave-operator/blob/main/docs/manifests/risingwave/risingwave-etcd-s3.yaml)
> docs: separate batch streaming modes

- docs/manifests/risingwave/advanced/separate-batch-streaming-modes.yaml
- docs/manifests/risingwave/risingwave-etcd-s3.yaml
> nit: remove redundant env

- README.md
> chore: update the kernel version from 1.5.0 to 1.6.0 in README

- .github/workflows/release.yml
- build/Dockerfile
- ci/runner/Dockerfile
> chore: bump to go 1.22

- docs/general/aws-eks-iam-for-s3.md
- docs/manifests/risingwave/advanced/separate-batch-streaming-modes.yaml
- docs/manifests/risingwave/risingwave-aliyun-oss.yaml
- docs/manifests/risingwave/risingwave-customize-config.yaml
- docs/manifests/risingwave/risingwave-etcd-auth.yaml
- docs/manifests/risingwave/risingwave-etcd-azure.yaml
- docs/manifests/risingwave/risingwave-etcd-local-disk.yaml
- docs/manifests/risingwave/risingwave-etcd-minio.yaml
- docs/manifests/risingwave/risingwave-etcd-s3.yaml
- docs/manifests/risingwave/risingwave-gcs.yaml
- docs/manifests/risingwave/risingwave-huaweicloud-obs.yaml
- docs/manifests/risingwave/risingwave-im-memory-azure.yaml
- docs/manifests/risingwave/risingwave-in-memory.yaml
- docs/manifests/risingwave/risingwave-s3-compatible.yaml
- docs/manifests/risingwave/risingwave-standalone.yaml
- docs/manifests/risingwavescaleview/sv-example-frontend.yaml
- docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
- docs/manifests/stable/memory/risingwave.yaml
- docs/manifests/stable/persistent/minio/risingwave.yaml
- docs/manifests/stable/persistent/s3/risingwave.yaml
- test/e2e/env
- test/e2e/tests/tests.sh
> chore: bump risingwave to v1.7.1

- docs/general/aws-eks-iam-for-s3.md
- docs/manifests/risingwave/advanced/separate-batch-streaming-modes.yaml
- docs/manifests/risingwave/risingwave-aliyun-oss.yaml
- docs/manifests/risingwave/risingwave-customize-config.yaml
- docs/manifests/risingwave/risingwave-etcd-auth.yaml
- docs/manifests/risingwave/risingwave-etcd-azure.yaml
- docs/manifests/risingwave/risingwave-etcd-local-disk.yaml
- docs/manifests/risingwave/risingwave-etcd-minio.yaml
- docs/manifests/risingwave/risingwave-etcd-s3.yaml
- docs/manifests/risingwave/risingwave-gcs.yaml
- docs/manifests/risingwave/risingwave-huaweicloud-obs.yaml
- docs/manifests/risingwave/risingwave-im-memory-azure.yaml
- docs/manifests/risingwave/risingwave-in-memory.yaml
- docs/manifests/risingwave/risingwave-s3-compatible.yaml
- docs/manifests/risingwave/risingwave-standalone.yaml
- docs/manifests/risingwavescaleview/sv-example-frontend.yaml
- docs/manifests/risingwavescaleview/sv-spot-compactor.yaml
- docs/manifests/stable/memory/risingwave.yaml
- docs/manifests/stable/persistent/minio/risingwave.yaml
- docs/manifests/stable/persistent/s3/risingwave.yaml
- test/e2e/env
- test/e2e/tests/tests.sh
> chore: bump risingwave to v1.7.2, favor docker.io instead of ghcr.io

- apis/risingwave/v1alpha1/risingwave_state_store_backend.go
- config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
- config/risingwave-operator-test.yaml
- config/risingwave-operator.yaml
- docs/general/api.md
> feat: allow http scheme for s3 endpoint

- pkg/factory/risingwave_object_factory.go
See https://github.com/risingwavelabs/risingwave/issues/16693 for the background.
TL;DR: As we cannot guarantee there's no (unexpected) synchronous I/O call within the asynchronous context in kernel's Rust code, increasing the worker threads number can reduce the possibility of the process being blocked, especially for the free-tier standalone deployment with CPU limit set to 1.
> fix: use a minimal value of 4 for `RW_WORKER_THREADS`

- .github/workflows/auto_update_helm_by_release.yml
> ci: add update helm pipeline

- pkg/factory/envs/risingwave.go
- pkg/factory/risingwave_object_factory.go
> feat: set RUST_MIN_STACK to 4194304

- Makefile
- apis/risingwave/v1alpha1/risingwave_types.go
- apis/risingwave/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
- config/risingwave-operator-test.yaml
- config/risingwave-operator.yaml
- docs/general/api.md
- pkg/factory/risingwave_object_factory.go
- pkg/object/risingwave_manager.go
- Added a flag `enableAdvertisingWithIP` to give users the choice of bypassing domain advertising. Verified locally.
> feat: support adversting with IP addresses, useful to avoid DNS problems

- docs/manifests/risingwave/advanced/separate-batch-streaming-modes.yaml
- docs/manifests/risingwave/risingwave-aliyun-oss.yaml
- docs/manifests/risingwave/risingwave-customize-config.yaml
- docs/manifests/risingwave/risingwave-etcd-auth.yaml
- docs/manifests/risingwave/risingwave-etcd-azure.yaml
- docs/manifests/risingwave/risingwave-etcd-hdfs.yaml
- docs/manifests/risingwave/risingwave-etcd-minio.yaml
- docs/manifests/risingwave/risingwave-etcd-s3.yaml
- docs/manifests/risingwave/risingwave-gcs.yaml
- docs/manifests/risingwave/risingwave-hdfs.yaml
- docs/manifests/risingwave/risingwave-huaweicloud-obs.yaml
- docs/manifests/risingwave/risingwave-mysql-s3.yaml
- docs/manifests/risingwave/risingwave-postgresql-s3.yaml
- docs/manifests/risingwave/risingwave-s3-compatible.yaml
- docs/manifests/risingwave/risingwave-sqlite-s3.yaml
- docs/manifests/stable/persistent/minio/risingwave.yaml
- docs/manifests/stable/persistent/s3/risingwave.yaml
> docs: fix MALLOC_CONF in examples

- pkg/factory/risingwave_object_factory.go
> fix: fix passing sqlite path

- apis/risingwave/v1alpha1/risingwave_types.go
- config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml
- config/risingwave-operator-test.yaml
- config/risingwave-operator.yaml
- docs/general/api.md
Change `StateFulSets` to `StatefulSets`.
> style: correct spelling of statefulset

- pkg/factory/risingwave_object_factory.go
> fix: allow overriding the RW_RESOURCE_GROUP

- pkg/webhook/risingwave_validating_webhook.go
- As title.
https://github.com/risingwavelabs/risingwave-operator/issues/884#issuecomment-3022834943
> fix: fix the error message on invalid meta store

- docs/manifests/stable/persistent/minio/risingwave.yaml
- docs/manifests/stable/persistent/s3/risingwave.yaml
- Add the PVC so that PG deployments can tolerate pod restarts
> docs: add persistent volume to PostgreSQL deployments
