config/manager/configmap.yaml, config/manager/manager.yaml, config/risingwave-operator.yaml
use `Always` pull policy for the latest image to ensure the image is latest.
=> chore: use Always pull policy

pkg/manager/compactor.go, pkg/manager/compute.go, pkg/manager/frontend.go, pkg/manager/meta.go
Liveness probe is required to check if the nodes are healthy. If not, they are restarted automatically.
This PR works by adding an additional "livenessProbe" field to the container struct during the deployment of these nodes.
Timeout seconds and other configurations for the probe are hard-coded at the moment. When mature, we should create a configuration file for all the other configurations including items such as Prometheus address and so forth.
#55
=> feat: add liveness-probe to meta, compute, frontend and compactor nodes

apis/risingwave/v1alpha1/risingwave_types.go, config/crd/bases/risingwave.singularity-data.com_risingwaves.yaml, config/risingwave-operator.yaml, examples/etcd-service.yaml, go.sum, pkg/controllers/risingwave/factory/risingwave_object_factory.go, pkg/manager/meta.go
Add etcd endpoint fields into meta node spec. This results in a new CRD for the risingwave CR. During initialization, the operator can use this new field to deploy the meta node with the necessary arguments to use an ETCD instance for storage.
#51
=> feat: add etcd support for meta node deployments

apis/risingwave/v1alpha1/risingwave_types.go, config/crd/bases/risingwave.singularity-data.com_risingwaves.yaml, pkg/controller/risingwave_controller.go
- Add a new print column "AGE", commonly printed in other resources, to tell how long a RisingWave object exists.
- Optimize the initialization progress by parallelizing the provision of components since they have a retry mechanism themselves
Before this optimization, it takes about 40 seconds for waiting components to be ready:
```bash
k get rw -w
NAME              RUNNING   STORAGE   AGE
test-risingwave   False     Memory    2s
test-risingwave   False     Memory    20s
test-risingwave   False     Memory    30s
test-risingwave   False     Memory    40s
test-risingwave   True      Memory    40s
test-risingwave   True …
```
=> feat(controller): parallelize the provision of components

.pre-commit-config.yaml, Makefile, apis/risingwave/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/risingwave.singularity-data.com_risingwaves.yaml, config/risingwave-operator-test.yaml, config/risingwave-operator.yaml
- Bump the `controller-gen` to [v0.9.1](https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.9.1)
- Generate the manifests and stubs
- Fix the pre-commit hook `go-imports` to ignore generated files
=> chore: bump controller-gen to v0.9.1, regenerate and fix pre-commit hook

apis/risingwave/v1alpha1/validater.go
Add webhook validation for storage type of meta node. When ETCD is chosen as the storage type, an etcd endpoint must be defined in the CR.
#85
=> feat: add validation for etcd endpoint

docs/rfc/0002_kubectl_rw.md
- Propose a kind of kubectl plugin: `kubectl-rw`
- User can use `kubectl-rw` to deploy and manage risingwave operator and DBs conveniently.
=> RFC:a kind of kubectl plugin

apis/risingwave/v1alpha1/risingwave_types.go, config/crd/bases/risingwave.singularity-data.com_risingwaves.yaml, config/risingwave-operator-test.yaml, config/risingwave-operator.yaml, pkg/controller/risingwave_controller.go, pkg/controller/risingwave_controller_test.go, pkg/ctrlkit/common.go, pkg/ctrlkit/optimize.go, pkg/ctrlkit/optimize_test.go, pkg/ctrlkit/shared.go, pkg/ctrlkit/shared_test.go, pkg/factory/risingwave_object_factory.go, pkg/factory/risingwave_object_factory_test.go, pkg/manager/risingwave_controller_manager.cm, pkg/manager/risingwave_controller_manager.go, pkg/manager/risingwave_controller_manager_impl.go
- Configure liveness probes on the component pods.
- Detect and recover the missing sub-resources.
- Detect missing services or workloads results in a transition of condition `Running` from `True` to `False`
- Try to recover all the components when `Running = False`
- Misc
- Add a new action decorator `Shared` for sharing actions, i.e. run exactly once regardless of how many times it executes and returns the same result for each execution.
- Add a new field `exists` in replicas status to indicate if the group exists now.
close #64
=> feat: recovery and failover

e2e/e2e.sh
Currently, if e2e-test failed, github action will still treat it as a sucessuful task: [example](https://github.com/singularity-data/risingwave-operator/runs/7495525061?check_suite_focus=true).
=> fix: e2e-test failed should exit with code 1

e2e/e2e.sh
- Fix the test script.
```shell
if [ $reap -eq 0 ]
```
causes an error `[: -eq: unary operator expected`, I think it should be `[[ $reap -eq 0 ]]` in bash. But anyway, `if reap` always works.
=> test(e2e): fix the test script

pkg/command/create/config/config.go, pkg/command/create/config/config_test.go, pkg/command/create/create.go, pkg/command/create/create_test.go, pkg/command/restart/restart.go, pkg/command/resume/resume.go, pkg/command/root.go, pkg/command/scale/scale.go, pkg/command/stop/stop.go
- Completed scale, stop and resume commands
- Stop and resume commands use annotations to store and restore replica numbers 
- Create POC for restart command
=> feat: complete scale, stop and resume commands

pkg/factory/risingwave_object_factory.go
- According to the kernel [code](https://github.com/singularity-data/risingwave/blob/613ed1a7a6faeefb8c6167b92989cb7bf46faa69/src/utils/runtime/src/lib.rs#L269-L292), there's an env variable `RW_WORKER_THREADS` that helps control the worker threads size. This PR supports setting the worker threads pool size with it if and only if there's a CPU limit on resources. The value is rounded up to the nearest integer away from 0, e.g. 100m results in 1, and 1.6 results in 2.
=> feat: set RW_WORKER_THREADS accroding to the resource limits

pkg/ctrlkit/join.go, pkg/ctrlkit/optimize.go, pkg/factory/common.go, pkg/factory/risingwave_object_factory.go, pkg/manager/risingwave_controller_manager_generated.go, pkg/utils/sort.go
- Fix the possible issue that would be caused by unstable lists in pod spec in the future, e.g., if there's an unstable `Volumes` list in the `Deployment` of frontend, syncing of replicas change might trigger a full rebuild of the Pods because of that.
- Comment formats introduced by go 1.19
=> fix: make sure the pod spec is stable by sorting the slices

pkg/consts/consts.go, pkg/factory/risingwave_object_factory.go, pkg/factory/risingwave_object_factory_test.go
- Some of the labels of RisingWave will be inherited, to sub-resources such as Service, ConfigMap, Deployment, StatefulSet, and the Pods controlled by the workload objects. The behavior is controlled with an annotation `risingwave.risingwavelabs.com/inherit-label-prefix`. The value of it should be a list of label prefixes separated by commas.
- Note: label prefix should omit the slash. 
```yaml
metadata:
name: risingwave-in-memory
labels:
risingwave.dev/user: abc123
annotations:
risingwave.risingwavelabs.com/inherit-label-prefix: risingwave.dev
```
NOTE: the Pods' labels are set by updating the pod template, so any …
=> feat: Support inheriting labels from RisingWave to sub-resources

Makefile
Explicitly use `docker buildx build` instead of `docker build`, because `docker build` seems to have issue with `--load` parameter.
=> use docker buildx build

.cspell/misc.txt, pkg/factory/risingwave_object_factory.go, pkg/factory/risingwave_object_factory_test.go
- In the PR risingwavelabs/risingwave#4966, the config `checkpoint_interval_ms` is deprecated, so the previous default config is no longer compatible. I decided to remove the default config so that the kernel will read an empty file and use the inner default configs.
- This also fixes the E2E tests.
NOTE: RisingWave versions before that will not be able to start with a default config after this is merged.
=> refactor: remove the default config

pkg/command/install/version/verison.go
- As title. This should fix the plugin e2e.
=> chore(plugin): update the default operator version to v0.2.2

cmd/manager/manager.go
- Set the value to false. Otherwise, the option is always enabled.
=> fix: fix the default value of `-enable-open-kruise` option

apis/risingwave/v1alpha1/risingwave_types.go, config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml, config/risingwave-operator-test.yaml, config/risingwave-operator.yaml, docs/general/api.md, pkg/factory/risingwave_object_factory.go, pkg/factory/risingwave_object_factory_test.go
- add the `priorityClassName` field to the `RisingWaveComponentGroupTemplate`
https://github.com/risingwavelabs/risingwave-operator/issues/259
=> feat: add the `priorityClassName` field to the `RisingWaveComponentGroupTemplate`

pkg/factory/risingwave_object_factory.go
- As title. `Floor` is a bug and will result in an incorrect value when the CPU limit isn't an integer.
=> fix: use ceil instead of floor

monitoring/install.sh, test/e2e/e2e.sh
Lets install all monitoring components in parallel. No need to wait for each of them individually.
=> feat(chore): install monitoring stack in parallel

.golangci.yaml, build/Dockerfile, go.mod
- Bump go toolchain to 1.20, and update the golangci config and Dockerfile
=> chore: bump go toolchain to 1.20

Makefile, README.md, docs/dev/rampup_example.md, docs/manifests/risingwave/risingwave-aliyun-oss.yaml, docs/manifests/risingwave/risingwave-component-groups.yaml, docs/manifests/risingwave/risingwave-component-only.yaml, docs/manifests/risingwave/risingwave-customize-config.yaml, docs/manifests/risingwave/risingwave-etcd-auth.yaml, docs/manifests/risingwave/risingwave-etcd-minio.yaml, docs/manifests/risingwave/risingwave-etcd-s3.yaml, docs/manifests/risingwave/risingwave-hdfs.yaml, docs/manifests/risingwave/risingwave-in-memory.yaml, docs/manifests/risingwave/risingwave-privileged.yaml, docs/manifests/risingwave/risingwave-s3-compatible.yaml, docs/manifests/risingwave/risingwave-spot-toleration.yaml, docs/manifests/risingwavescaleview/sv-example-frontend.yaml, docs/manifests/risingwavescaleview/sv-spot-compactor.yaml, e2e/env-utils, hack/scripts/install.sh, pkg/factory/risingwave_object_factory.go, pkg/factory/risingwave_object_factory_test.go, pkg/utils/common_test.go, test/e2e/e2e.sh, test/e2e/env, test/e2e/testenv/lib.sh, test/e2e/tests/risingwave/manifests/connector/connector-test.yaml, test/e2e/tests/risingwave/manifests/multi-meta/multi-meta.yaml, test/e2e/tests/tests.sh
- Use `--listen-addr` and `--advertise-addr`, deprecate the usages of `--host` and `--client-addr`.(https://github.com/risingwavelabs/risingwave/issues/7625, https://github.com/risingwavelabs/risingwave/issues/7678)
- Move the `--state-store` and credential envs to the meta nodes. (https://github.com/risingwavelabs/risingwave/issues/7860)
- Update the image versions to use `v0.1.17`
- Fix the `kubectl apply` in e2e tests and README
After this change, the minimum supported RisingWave version is `v0.1.17`.
fix CLOUD-988 CLOUD-989 CLOUD-990 CLOUD-991 CLOUD-992 CLOUD-899
=> fix: use new arguments

pkg/factory/risingwave_object_factory.go, pkg/factory/risingwave_object_factory_testcases_test.go
Kernel will reserve memory of the min size of `total_available_memory` and `512M`, so this PR aims to
- simplify memory limit computation in RisingWaveObjectFactory by removing conditional statements and always using memLimit. Update corresponding test cases to reflect this change.
=> fix: pass total available memory to the compute process

config/crd/bases/risingwave.risingwavelabs.com_risingwavepodtemplates.yaml, config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml, config/crd/bases/risingwave.risingwavelabs.com_risingwavescaleviews.yaml, config/risingwave-operator-test.yaml, config/risingwave-operator.yaml, hack/cspell/dicts/misc.txt, pkg/consts/consts.go, pkg/controller/meta_pod_role_labeler.go, pkg/factory/envs/risingwave.go, pkg/factory/envs/system.go, pkg/factory/risingwave_object_factory.go, pkg/factory/risingwave_object_factory_common_test.go, pkg/factory/risingwave_object_factory_predicate_test.go, pkg/factory/risingwave_object_factory_test.go, pkg/factory/risingwave_object_factory_testcases_test.go, pkg/webhook/risingwave_validating_webhook.go, test/e2e/tests/risingwave/meta.sh
- Use env-based options to start RisingWave processes. Deprecate the CLI arguments way.
- Move env name constants to a separate package `pkg/factory/envs`.
- Update the tests accordingly.
In this way, backward-compatibility is way easier to maintain because naturally the environment variables require a semantic of optional. For example, there are two environment variables representing the same option but exclusively used by different versions:
- `META_ADDRESS` by `v0.1.17` only
- `META_ADDR` by `v0.1.18-rc` and after versions
The operator can now deploy both versions without worrying of incompatibilities. The PR passed all e2e tests locally.
=> refactor(factory): use env options

pkg/factory/risingwave_object_factory.go
As the title.
https://linear.app/risingwave-labs/issue/CLOUD-1211/bug-not-getting-any-analytics-datacpumemorythroughput-from-api-for-all
=> fix(metrics): add metrics port env for compute node(CLOUD-1211)

apis/risingwave/v1alpha1/risingwave_types.go, config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml, config/risingwave-operator-test.yaml, config/risingwave-operator.yaml, docs/general/api.md, pkg/factory/risingwave_object_factory.go, pkg/factory/risingwave_object_factory_testcases_test.go
- Add a field `.spec.storages.object.dataDirectory` to specify the data directory option on CR
Kind reminder: the legacy way of setting this option will be completely deprecated and will take no effect after this changes merged, cc. @mikechesterwang @wjf3121
=> feat: add a new field dataDirectory to specify the directory directly

Makefile, docs/dev/development.md
Hi, 
This PR is to fix the image url in Makefile when using `make docker-build`. 
I modified the image url based on the development guide.
=> build: fix the image url

docs/general/storage.md, docs/manifests/risingwave/risingwave-etcd-hdfs.yaml
At #426, I provide the in memory + hdfs configure file. But I find in our official website docs, we provide etcd + XXX as the example. In order to keep consistency with other examples, I provide another example here by using etcd as metadata storage type.
=> docs: add etcd hdfs yaml

docs/manifests/risingwave/risingwave-etcd-local-disk.yaml, test/e2e/tests/risingwave/manifests/storages/local-disk.yaml
> > @hzxa21 Is it true that meta nodes won't query against state store directly. If so, then the example here works perfectly because I excluded the volume mounting of the data directory from the meta's Pod. Otherwise, I need to revise it.
> 
> meta node will not query against state store but it will contact object store backend to store the version checkpoint and backup states so I think making sure meta can read from and write to the object store data directory is neccessary. cc @zwang28
- Mount the data directory on the meta Pod.
#439
=> docs & ci: fix manifests of local disk deployments

apis/risingwave/v1alpha1/risingwave_state_store_backend.go, config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml, config/risingwave-operator-test.yaml, config/risingwave-operator.yaml, docs/general/api.md, pkg/webhook/risingwave_conversion.go
- Set the default data directory to `hummock` if it's not provided. It will mitigate the problems mentioned in #441 
- Note that this change will affect any existing RisingWave objects if they have an empty data directory. 
fix #441
=> fix: set a default data directory instead of empty

docs/manifests/risingwave/risingwave-etcd-s3.yaml
As risingwave does not allow an empty data directory or a data directory that has already been used to avoid confusion, some users ask how they can change it when they deploy RW via k8s.
=> remind users to adjust data directory just in case

pkg/factory/risingwave_object_factory.go, pkg/factory/risingwave_object_factory_testcases_test.go
- Before this change, the Recreate upgrade type has no effect. But it does mean we don't care about how many Pods will be alive during the upgrading so it's more appropriate to set it to `rollingUpgrade` with `maxUnavaialbe` equals to `100%`.
=> refactor: reflect recreate upgrade type on sts

monitoring/README.md
Add instructions for Grafana to accept requests from external hosts via `kubectl port-forward`
=> doc: Grafana accept requests from external hosts

docs/manifests/stable/persistent/minio/risingwave.yaml, docs/manifests/stable/persistent/s3/risingwave.yaml
These two yaml files are the default ones that get used by users, e.g. reading README.md in this Repo or reading documentation at risingwave.dev.
I think we can start the connector node by default as it is a must for `postgres-cdc` and other advanced sources/sinks.
They typically encounter `transport error` when they try to establish source without starting a connector node.
Try to reduce the friction and confusion.
=> start connector node by default

pkg/factory/risingwave_object_factory.go
- As title. Using startup probe can prevent pods from restarting when meta isn't fully initialized. It helps bootstrapping a RisingWave cluster more smoothly.
- Note that this is a change that will affect existing clusters: after any kind of manifest operations, all RisingWave pods will get recreated.
=> feat: set startup probe to prevent from unnecessary restarts

monitoring/README.md, monitoring/install.sh
The idea is that users can directly call the command for installation. I've tested the script, and it ran successfully. However I was not able to export the port 3000 because it kept pending.
```
kubectl port-forward -n monitoring svc/prometheus-grafana 3000:http-web
error: unable to forward port because pod is not running. Current status=Pending
```
=> eliminate the need to clone the repo in order to install monitoring

pkg/factory/envs/risingwave.go, pkg/factory/risingwave_object_factory.go
https://github.com/risingwavelabs/risingwave/pull/12099
The above PR changes the default value of this environment variable to 'info', 1 is an invalid value.
=> chore: remove RW_METRICS_LEVEL env

pkg/factory/risingwave_object_factory.go
As title. `risectl` will use `RW_META_ADDR` to connect to Meta Node. For Meta node itself, the address is localhost
=> feat: set RW_META_ADDR in meta pod, used by risectl

docs/manifests/risingwave/risingwave-aliyun-oss.yaml, docs/manifests/risingwave/risingwave-azure.yaml, docs/manifests/risingwave/risingwave-customize-config.yaml, docs/manifests/risingwave/risingwave-etcd-auth.yaml, docs/manifests/risingwave/risingwave-etcd-hdfs.yaml, docs/manifests/risingwave/risingwave-etcd-local-disk.yaml, docs/manifests/risingwave/risingwave-etcd-minio.yaml, docs/manifests/risingwave/risingwave-etcd-s3.yaml, docs/manifests/risingwave/risingwave-gcs.yaml, docs/manifests/risingwave/risingwave-hdfs.yaml, docs/manifests/risingwave/risingwave-in-memory.yaml, docs/manifests/risingwave/risingwave-s3-compatible.yaml, docs/manifests/stable/memory/risingwave.yaml, docs/manifests/stable/persistent/minio/risingwave.yaml, docs/manifests/stable/persistent/s3/risingwave.yaml
Update all YAML examples: add resource (cpu/memory) request & limit.
> If the memory limit is not set correctly, the cluster will OOM frequently, because every Pod thinks it has full memory to use.
=> chore: fix resource limit

docs/manifests/risingwave/risingwave-aliyun-oss.yaml, docs/manifests/risingwave/risingwave-customize-config.yaml, docs/manifests/risingwave/risingwave-etcd-auth.yaml, docs/manifests/risingwave/risingwave-etcd-azure.yaml, docs/manifests/risingwave/risingwave-etcd-hdfs.yaml, docs/manifests/risingwave/risingwave-etcd-minio.yaml, docs/manifests/risingwave/risingwave-etcd-s3.yaml, docs/manifests/risingwave/risingwave-gcs.yaml, docs/manifests/risingwave/risingwave-hdfs.yaml, docs/manifests/risingwave/risingwave-s3-compatible.yaml, docs/manifests/stable/persistent/minio/risingwave.yaml, docs/manifests/stable/persistent/s3/risingwave.yaml
- Update most of the example manifests to enable the heap profiling on meta/frontend/compute nodes. Details:
- `lg_prof_sample` are all 20
- Files will be stored under `/heap`, which is backed by [emptyDir](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir).
- Size limit is `1Gi`. Note it might or might not take effect. It depends on the local file system.
The following files were not changed:
- Memory based deployments
- Local disk state store (experimental)
=> docs: add emptydir for heap profiling

cmd/manager/manager.go, pkg/controller/risingwave_compute_sts_update_strategy.go, pkg/utils/common.go
- Add an external policy that targets the **compute StatefulSet** only in order to accelerate the upgrade process by deleting the outdated Pods
Rationale
- Restarting of any compute nodes will result in a failover of all streaming jobs by design, cc. @fuyufjh for confirmation if it will change in the future.
- Max unavailable in rolling upgrade strategy doesn't apply to StatefulSet. The controller will always upgrade Pods one by one in an reversed order. https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#rolling-updates
- Parallel pod management policy only affects the behavior for scaling operations. Updates are not affected. Reference: …
=> feat: accelerate upgrade of compute sts with an external policy

README.md, docs/general/aws-eks-iam-for-s3.md, docs/manifests/risingwave/risingwave-aliyun-oss.yaml, docs/manifests/risingwave/risingwave-customize-config.yaml, docs/manifests/risingwave/risingwave-etcd-auth.yaml, docs/manifests/risingwave/risingwave-etcd-azure.yaml, docs/manifests/risingwave/risingwave-etcd-local-disk.yaml, docs/manifests/risingwave/risingwave-etcd-minio.yaml, docs/manifests/risingwave/risingwave-etcd-s3.yaml, docs/manifests/risingwave/risingwave-gcs.yaml, docs/manifests/risingwave/risingwave-im-memory-azure.yaml, docs/manifests/risingwave/risingwave-in-memory.yaml, docs/manifests/risingwave/risingwave-s3-compatible.yaml, docs/manifests/risingwavescaleview/sv-example-frontend.yaml, docs/manifests/risingwavescaleview/sv-spot-compactor.yaml, docs/manifests/stable/memory/risingwave.yaml, docs/manifests/stable/persistent/minio/risingwave.yaml, docs/manifests/stable/persistent/s3/risingwave.yaml, test/e2e/env, test/e2e/tests/tests.sh
=> chore: bump kernel to v1.4.0

apis/risingwave/v1alpha1/risingwave_standalone_mode.go, config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml, config/risingwave-operator-test.yaml, config/risingwave-operator.yaml
This fixes programatic patching on the field.
- As title. Before the change, set the replicas to 0 and then with `MergeFrom` it will generate a patch like 
```json
{"spec":{"components":{"standalone":{"replicas":null}}}}
```
However, there's a default value `1` on the field so the patch actually does nothing. Remove the `omitempty` to avoid that. 
It's verified that after the change the patch looks like 
```json
{"spec":{"components":{"standalone":{"replicas":0}}}}
```
and it works well.
The change won't change the YAML compatibility since there's a default on the field.
=> Mark .spec.components.standalone.replicas as required. 

monitoring/kube-prometheus-stack.yaml
The actor-level stream exchange metrics are already removed in the kernel. https://github.com/risingwavelabs/risingwave/issues/7362
The fragment-level metrics are small, just like other metrics on Grafana
In the future, if any metrics are too large to be collected, stored, or shown, I'll ask the kernel to do it.
=> reenable stream frag exchange

pkg/factory/risingwave_object_factory.go
Fix this problem:
```
root@benchmark-risingwave-meta-m-0:/risingwave/bin# ./risingwave ctl profile cpu --sleep 10
launching `ctl`
2024-01-26T05:40:23.291957186Z  INFO risingwave_ctl::common::meta_service: using meta addr from `RW_META_ADDR`: 127.0.0.1:5690
2024-01-26T05:40:23.292125303Z  INFO risingwave_rpc_client::meta_client: register meta client using strategy: 127.0.0.1:5690
2024-01-26T05:40:23.292539856Z  WARN risingwave_rpc_client::meta_client: Failed to connect to meta server 127.0.0.1:5690, trying again error=transport error: error trying to connect: invalid URL, scheme is missing
2024-01-26T05:40:23.332969831Z  WARN risingwave_rpc_client::meta_client: Failed to connect to meta server 127.0.0.1:5690, trying again error=transport error: error trying to connect: invalid URL, scheme …
```
=> fix: RW_META_ADDR for meta node (for locally accessed from risectl)

go.mod, pkg/controller/meta_pod_role_labeler.go
This moves the pod filtering logic for the meta label from the reconciliation func to the controller, micro optimisation to not run unnecessary reconciliation on pods that do not need it.
- movement of pod filtering in meta role labeler from within the reconciliation, into the filter func of the controller builder
- [ x] I have written the necessary docs and comments
- [x ] I have added necessary unit tests and integration tests
=> refactor: use ctrl runtime library func optimisation

apis/risingwave/v1alpha1/risingwave_node_group.go, config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml, config/risingwave-operator-test.yaml, config/risingwave-operator.yaml
- After bumping the `controller-gen` tool, the `+kubebuilder:validation:Required` mark takes effect correctly. And the field `replicas` under node group is incorrectly marked. Removing the mark resolves the following error when creating a `RisingWave` object if one of the `replicas` is set to 0:
```
The RisingWave "risingwave-in-memory" is invalid: spec.components.compute.nodeGroups[1].replicas: Required value
```
=> fix: remove the required mark for replicas field

pkg/features/feature_manager.go
- The feature gate is used for handling conflicts when updating an k8s object, e.g., adding a PVC template in the meta/compute STS. The controller will delete the resource first and create it afterwards whenever there's a conflict.
=> feat: turn the feature gate EnableForceUpdate on by default

docs/manifests/risingwave/risingwave-postgresql-local-disk.yaml
Added a new YAML file that has postgres as the metastore, but is otherwise similar to `risingwave-etcd-local-disk.yaml`
=> YAML chart for using Postgres as metastore and local-disk as storage backend

pkg/factory/envs/risingwave.go, pkg/factory/risingwave_object_factory.go, pkg/factory/risingwave_object_factory_test.go
The resource group of a compute container should always be the same as the group name it is part of. 
https://linear.app/risingwave-labs/issue/CLOUD-3673/feature-resource-group-support-in-the-rw-operator
Very short demo: 
https://github.com/user-attachments/assets/b02b5202-60fa-427b-9019-9b17872cdda7
=> feat: Support resource groups

pkg/factory/risingwave_object_factory.go, pkg/factory/risingwave_object_factory_testcases_test.go
The `endpoint` field description explicitly allows both HTTP and HTTPS schemes, with HTTPS being the default if no scheme is provided. However, the code previously enforced HTTPS unconditionally by prepending `https://` even when `http://` was explicitly provided.
=> fix: respect http scheme in S3 endpoint field

apis/risingwave/v1alpha1/risingwave_types.go, apis/risingwave/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/risingwave.risingwavelabs.com_risingwaves.yaml, config/risingwave-operator-test.yaml, config/risingwave-operator.yaml, docs/general/api.md, pkg/consts/consts.go, pkg/factory/envs/risingwave.go, pkg/factory/risingwave_object_factory.go, pkg/factory/risingwave_object_factory_predicate_test.go, pkg/factory/risingwave_object_factory_test.go, pkg/factory/risingwave_object_factory_testcases_test.go
- Add an option to enable the webhook listener of serving nodes. It defaults to listen on 0.0.0.0:4560.
=> feat: support enabling webook listener
